using System.Runtime.InteropServices;

namespace Weft.Yrs;

/// <summary>
/// P/Invoke declarations over the C-ABI of the <c>weft-yrs-ffi</c> shim, generated by the source
/// generator <see cref="LibraryImportAttribute"/> (compile-time marshalling, no IL stubs).
/// They must match <c>native/weft-yrs-ffi/include/weft_ffi.h</c>, which is the source of truth of the
/// contract; <c>HeaderBindingParityTests</c> validates it (syntactic parity: function set,
/// arity, order and types — not the semantics or ownership, which ASan and the round-trips cover).
/// </summary>
/// <remarks>
/// Marshalling conventions: INPUT bytes as <see cref="ReadOnlySpan{Byte}"/> (automatic pin,
/// zero copies); OUTPUT bytes as <c>out nint</c> + <c>out nuint</c> (Rust memory,
/// copied to managed and freed with <see cref="weft_buf_free"/>); document as
/// a raw <c>nint</c> lent by <see cref="HandleLease"/> (SYSLIB1051, research R2).
/// </remarks>
internal static partial class NativeMethods
{
    internal const string Lib = "weft_yrs_ffi";

    // ── Lifecycle ──
    [LibraryImport(Lib)]
    internal static partial int weft_doc_new(out nint outDoc);

    [LibraryImport(Lib)]
    internal static partial int weft_doc_new_with_client_id(ulong clientId, out nint outDoc);

    [LibraryImport(Lib)]
    internal static partial int weft_doc_load(ReadOnlySpan<byte> blob, nuint blobLen, out nint outDoc);

    [LibraryImport(Lib)]
    internal static partial void weft_doc_free(nint doc);

    // ── Text ──
    [LibraryImport(Lib)]
    internal static partial int weft_text_insert(
        nint doc, ReadOnlySpan<byte> field, nuint fieldLen,
        uint index, ReadOnlySpan<byte> text, nuint textLen);

    [LibraryImport(Lib)]
    internal static partial int weft_text_delete(
        nint doc, ReadOnlySpan<byte> field, nuint fieldLen, uint index, uint len);

    [LibraryImport(Lib)]
    internal static partial int weft_text_read(
        nint doc, ReadOnlySpan<byte> field, nuint fieldLen, out nint outPtr, out nuint outLen);

    // ── State and synchronization ──
    [LibraryImport(Lib)]
    internal static partial int weft_doc_export_state(nint doc, out nint outPtr, out nuint outLen);

    [LibraryImport(Lib)]
    internal static partial int weft_doc_state_vector(nint doc, out nint outPtr, out nuint outLen);

    [LibraryImport(Lib)]
    internal static partial int weft_doc_export_since(
        nint doc, ReadOnlySpan<byte> sv, nuint svLen, out nint outPtr, out nuint outLen);

    [LibraryImport(Lib)]
    internal static partial int weft_doc_apply_update(nint doc, ReadOnlySpan<byte> update, nuint updateLen);

    // ── Memory ──
    [LibraryImport(Lib)]
    internal static partial void weft_buf_free(nint ptr, nuint len);

    // ── Diagnostics ──
    [LibraryImport(Lib)]
    internal static partial uint weft_abi_version();
}
