using Microsoft.EntityFrameworkCore;

namespace Weft.Server.Persistence.EFCore;

/// <summary>Kind of persisted record: distinguishes the consolidated snapshot from an incremental update.</summary>
internal enum RecordKind : byte
{
    /// <summary>Consolidated snapshot of the document (at most one per doc; it is the base of the framing).</summary>
    Snapshot = 0,

    /// <summary>Incremental update accumulated on top of the snapshot, in order of <see cref="DocumentRecord.Seq"/>.</summary>
    Update = 1,
}

/// <summary>
/// Durable state row of a document. The <see cref="Payload"/> is an <b>opaque</b> blob (P-IV): EF Core
/// never interprets yrs bytes. The reconstruction order is fixed by <see cref="Seq"/> (monotonic per doc).
/// </summary>
internal sealed class DocumentRecord
{
    /// <summary>Surrogate primary key generated by the database.</summary>
    public long Id { get; set; }

    /// <summary>Opaque document identifier (may contain any character).</summary>
    public string DocId { get; set; } = default!;

    /// <summary>Ordering index within the document; the snapshot is the base and updates grow from there.</summary>
    public long Seq { get; set; }

    /// <summary>Snapshot or update.</summary>
    public RecordKind Kind { get; set; }

    /// <summary>Opaque bytes of the record (consolidated snapshot or a single incremental update).</summary>
    public byte[] Payload { get; set; } = default!;
}

/// <summary>
/// <see cref="DbContext"/> for the <see cref="EFCoreDocumentStore"/> adapter. Maps a single record table
/// (<c>WeftDocumentRecords</c>) indexed by <c>(DocId, Seq)</c>. The provider (SQLite, PostgreSQL, …) is chosen
/// by the consumer via <see cref="DbContextOptions"/>; this context is provider-agnostic.
/// </summary>
public sealed class WeftDocumentStoreContext : DbContext
{
    /// <summary>Creates the context with the consumer's options (provider + connection string).</summary>
    public WeftDocumentStoreContext(DbContextOptions<WeftDocumentStoreContext> options)
        : base(options)
    {
    }

    internal DbSet<DocumentRecord> Records => Set<DocumentRecord>();

    /// <inheritdoc />
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        ArgumentNullException.ThrowIfNull(modelBuilder);

        var record = modelBuilder.Entity<DocumentRecord>();
        record.ToTable("WeftDocumentRecords");
        record.HasKey(r => r.Id);
        record.Property(r => r.DocId).IsRequired();
        record.Property(r => r.Payload).IsRequired();
        // Access is always "all records of a doc, in Seq order": a composite index that covers it.
        record.HasIndex(r => new { r.DocId, r.Seq });
    }
}
